config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :restaurants, :cuisines, :reviews

  root :to => 'app#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # scoping
  scope :sorted_by_name_asc, -> { order('name ASC') }

end

app/models/cuisine.rb
# == Schema Information
#
# Table name: cuisines
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cuisine < ApplicationRecord

  has_many :restaurants

end

app/models/restaurant.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: restaurants
#
#  id            :bigint(8)        not null, primary key
#  name          :string
#  cuisine_id    :integer
#  rating        :integer
#  ten_bis       :boolean          default(FALSE)
#  address       :string
#  delivery_time :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Restaurant < ApplicationRecord

  belongs_to :cuisine
  has_many :reviews

  # data validations:
  validates_presence_of :name

  def update_rating!
    self.rating = reviews.empty? ? 0 : (reviews.sum(:rating) / reviews.length)
    save!
  end

end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id            :bigint(8)        not null, primary key
#  restaurant_id :integer
#  rating        :integer
#  summary       :string           not null
#  full_review   :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Review < ApplicationRecord

  belongs_to :restaurant

  after_save :update_restaurant_rating!
  after_destroy :update_restaurant_rating!

  private

  def update_restaurant_rating!
    restaurant.update_rating!
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base

  skip_before_action :verify_authenticity_token

  def root
    render inline: '', layout: 'application'
  end
end

app/controllers/cuisine_controller.rb
class CuisineController < ApplicationController

  before_action :find_related_restaurants, :only => [:delete, :destroy]

  def index
    @cuisines = Cuisine.sorted
  end

  def show
    @cuisine = Cuisine.find(params.require(:id))
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.create!(cuisine_params)
    if @cuisine
      flash[:notice] = "New cuisine was saved"
      redirect_to(new_restaurant_path)
    else
      flash.now[:notice] = "Could not create new cuisine"
      render('new')
    end
  end

  def edit
    @cuisine = Cuisine.find(params.require(:id))
  end

  def update
    @cuisine = Cuisine.find(params.require(:id))
    if @cuisine.update_attributes(cuisine_params)
      flash[:notice] = "Cuisine #{ @cuisine.name } was updated"
      redirect_to(cuisine_index_path)
    else
      @flash.now[:notice] = "Issue with updating cuisine"
      render('edit')
    end
  end

  def delete
    @cuisine = Cuisine.find(params.require(:id))
  end

  def destroy
    @cuisine = Cuisine.find(params.require(:id))

    if @restaurants.size > 0
      flash.now[:notice] = "Couldn't delete a cuisine with restaurants associate to it"
      render('delete')
    else
      @cuisine.destroy
      flash[:notice] = "Cuisine #{ @cuisine.name } was deleted"
      redirect_to(cuisine_index_path)
    end
  end

  private

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end

  def find_related_restaurants
    @restaurants = Restaurant.where("cuisine_id = #{ params.require(:id) }")
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController

  def index
    render json: Cuisine.sorted_by_name_asc
  end

  def show
    render json: Cuisine.find(params[:id])
  end

  def create
    render json: Cuisine.create!(cuisine_params), status: :created
  end

  def update
    render json: Cuisine.find(params[:id]).update!(cuisine_params), status: :accepted
  end

  def destroy
    render json: Cuisine.find(params[:id]).destroy!, status: :accepted
  end

  private

  def cuisine_params
    params.require(:cuisine).permit(:name, :image_url)
  end
end

app/controllers/restaurant_controller.rb
# frozen_string_literal: true

class RestaurantController < ApplicationController

  before_action :set_cuisines, :except => [:show, :delete, :destroy]

  def index
    @restaurants = Restaurant.sorted
  end

  def show
    @restaurant = Restaurant.find(params.require(:id))
  end

  def new
    @restaurant = Restaurant.new({:name => 'Default'})
  end

  def create
    @restaurant = Restaurant.create!(restaurant_params)
    if @restaurant
      flash[:notice] = "New restaurant - #{@restaurant.name} was saved."
      redirect_to(restaurant_index_path)
    else
      flash.now[:notice] = "Error occur while saving new restaurant - #{@restaurant.name} : #{@restaurant.errors.full_messages}"
      render('new')
    end
  end

  def edit
    @restaurant = Restaurant.find(params.require(:id))
  end

  def update
    @restaurant = Restaurant.find(params.require(:id))
    if @restaurant.update_attributes(restaurant_params)
      flash[:notice] = "Restaurant - #{@restaurant.name} was updated."
      redirect_to(restaurant_index_path)
    else
      flash.now[:notice] = "Couldn't update restaurant #{@restaurant.name}"
      render('edit')
    end
  end

  def delete
    @restaurant = Restaurant.find(params.require(:id))
  end

  def destroy
    @restaurant = Restaurant.find(params.require(:id))
    flash[:notice] = "Restaurant - #{@restaurant.name} was deleted."
    @restaurant.destroy
    redirect_to(restaurant_index_path)
  end


  private

  def restaurant_params
    params.require(:restaurant)
        .permit(:name, :cuisine_id, :address, :rating, :delivery_time, :ten_bis)
  end

  def set_cuisines
    @cuisines = Cuisine.sorted
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    render json: Restaurant.sorted_by_name_asc
  end

  def show
    render json: Restaurant.find(params[:id])
  end

  def create
    render json: Restaurant.create!(restaurant_params), status: :created
  end

  def update
    render json: Restaurant.find(params[:id]).update!(restaurant_params), status: :accepted
  end

  def destroy
    render json: Restaurant.find(params[:id]).destroy!, status: :accepted
  end

  private

  def restaurant_params
    params.require(:restaurant)
        .permit(:name, :cuisine_id, :address, :delivery_time, :ten_bis)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    restaurant_id = params.require(:restaurant_id)
    render json: Review.where(:restaurant_id => restaurant_id)
  end

  def show
    render json: Review.find(params[:id])
  end

  def create
    render json: Review.create!(review_params), status: :created
  end

  def update
    render json: Review.find(params[:id]).update!(review_params), status: :accepted
  end

  def destroy
    render json: Review.find(params[:id]).destroy!, status: :accepted
  end

  private

  def review_params
    params.require(:review).permit(:rating, :summary, :full_review, :user_id, :restaurant_id)
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cuisine_helper.rb
module CuisineHelper
end

app/helpers/restaurant_helper.rb
# frozen_string_literal: true

module RestaurantHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/cuisine/delete.html.erb
<%= link_to("<< Go to Cuisines List", cuisine_index_path, :class => 'back-line') %>

<% if !flash[:notice].blank? %>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>


<div class="cuisine delete" xmlns="http://www.w3.org/1999/html">
  <h2>Delete Cuisine</h2>

  <%= form_for(@cuisine, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this cuisine?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <% if @restaurants.size > 0 %>
      <p> The following restaurants are linked to this cuisine:</p>

      <table class="restuarants table edit">
        <% @restaurants.each do |r| %>
          <tr>
            <td> <%= r.name %> </td>
            <td> <%= link_to("Edit", edit_restaurant_path) %> </td>
          </tr>
        <% end %>
      </table>
    <% end %>

    <br />
    <br />

    <div class="form-buttons">
      <%= f.submit("Delete Cuisine") %>
    </div>

  <% end %>
</div>

app/views/cuisine/edit.html.erb
<%= link_to("<< Go to Cuisines List", cuisine_index_path, :class => 'back-line') %>

<div class="cuisine edit">
  <h2>Update Cuisine</h2>

  <%= form_for(@cuisine) do |f| %>

    <%= render(:partial => 'cuisine_form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Cuisine") %>
    </div>
  <% end %>
</div>

app/views/cuisine/new.html.erb
<%= link_to("<< Go to Cuisines List", cuisine_index_path, :class => 'back-line') %>

<div class="cuisine new">
  <h2>Create Cuisine</h2>

  <%= form_for(@cuisine, :url => cuisine_index_path) do |f| %>

    <%= render(:partial => 'cuisine_form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Cuisine") %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeEat</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application' %>
  <%= stylesheet_link_tag  'DynamicBar' %>
  <%= stylesheet_link_tag  'Restaurants' %>
  <%= stylesheet_link_tag  'InteractiveMap' %>

</head>

<body>
</body>
</html>

app/views/restaurant/delete.html.erb
<%= link_to("<< Back to List", restaurant_index_path, :class => 'back-link') %>

<div class="restaurant delete">
  <h2>Delete Restaurant</h2>

  <%= form_for(@restaurant, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this restaurant?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Restaurant") %>
    </div>

  <% end %>
</div>

app/views/restaurant/edit.html.erb
<%= link_to("<< Back to List", restaurant_index_path, :class => 'back-line') %>

<div class="restaurant edit">
  <h2>Update Restaurant</h2>

  <%= form_for(@restaurant) do |f| %>
    <%= render(:partial => 'restaurant_form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Restaurant") %>
    </div>
  <% end %>
</div>

app/views/restaurant/index.html.erb
<% if !flash[:notice].blank? %>
<div class="notice">
  <%= flash[:notice] %>
</div>
<% end %>

<div class="restaurant index">
  <h2>Restaurants</h2>

  <%= link_to("Add New Restaurant", new_restaurant_path, :class => 'action new') %>

  <table class="listing" summary="Restaurant list">
    <tr class="header">
      <th>#</th>
      <th>Restaurant</th>
      <th><%= link_to("Cuisine", cuisine_index_path, html_options = { title: "Update cuisines table" }) %></th>
      <th>Rating</th>
      <th>10bis?</th>
      <th>Address</th>
      <th>Delivery Time</th>
      <th>Actions</th>
    </tr>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.id %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.cuisine.name %></td>
        <td><%= restaurant.rating %></td>
        <td><%= restaurant.ten_bis ? 'Yes' : 'No'%></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.delivery_time %></td>
        <td class="actions">
          <%= link_to("Show", restaurant_path(restaurant), :class => 'action show') %>
          <%= link_to("Edit", edit_restaurant_path(restaurant), :class => 'action edit') %>
          <%= link_to("Delete", delete_restaurant_path(restaurant), :class => 'action delete') %>
        </td>

      </tr>
    <% end %>
  </table>
</div>

app/views/restaurant/new.html.erb
<%= link_to("<< Back to List", restaurant_index_path, :class => 'back-line') %>

<div class="restaurant new">
  <h2>Create Restaurant</h2>

  <%= form_for(@restaurant, :url => restaurant_index_path) do |f| %>

    <%= render(:partial => 'restaurant_form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Restaurant") %>
    </div>
  <% end %>
</div>

app/views/restaurant/show.html.erb
<%= link_to("<< Back to List", restaurant_index_path, :class => 'back-link') %>

<div class="restaurant show">
  <h2>Show Restaurant</h2>

  <table summary="Restaurant detail view">
    <tr>
      <th>Name</th>
      <td><%= @restaurant.name %></td>
    </tr>
    <tr>
      <th>Cuisine</th>
      <td><%= @restaurant.cuisine.name %></td>
    </tr>
    <tr>
      <th>Rating</th>
      <td><%= @restaurant.rating %></td>
    </tr>
    <tr>
      <th>Accept 10bis?</th>
      <td><%= @restaurant.ten_bis ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Address</th>
      <td><%= @restaurant.address%></td>
    </tr>
    <tr>
      <th>Delivery Time</th>
      <td><%= @restaurant.delivery_time %></td>
    </tr>
  </table>

</div>